- name: Frontend Setup
  hosts: all
  tasks:
    - name: Installing Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Placing Expense Config File in Nginx
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Removing Old Nginx Content
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Download frontend Code
      ansible.builtin.get_url:
        url: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /tmp/frontend.zip


   # - name: Extracting frontend Code
    #- name: Starting nginx Service


  #download_and_extract()
  #{
   # echo Download $component Code
    #curl -o /tmp/$component.zip https://expense-artifacts.s3.amazonaws.com/$component.zip >>$log_file
    #stat_check

   # echo Extracting $component Code
    #unzip /tmp/$component.zip >>$log_file
    #stat_check
  #}

    #source common.sh

    #component=frontend
    #echo Installing Nginx

    #dnf install nginx -y &>>$log_file

    #stat_check

    #echo Placing Expense Config File in Nginx
    #cp expense.conf /etc/nginx/default.d/expense.conf &>>$log_file
    #stat_check

    #echo Removing Old Nginx Content

    #rm -rf /usr/share/nginx/html/* &>>$log_file
    #stat_check

    #cd /usr/share/nginx/html

    #download_and_extract

    #echo Starting nginx Service
    #systemctl enable nginx &>>$log_file
    #systemctl restart nginx &>>$log_file
    #stat_check